### PR TITLE
fix mqtts semver

### PR DESCRIPTION
**Pull request by f0rr0**
`mqtts` published a breaking change as minor version.

In https://github.com/Nerixyz/mqtts/pull/24 `autoReconnect` should ideally be left as a boolean and another arg `reconnectStrategy` might be introduced for semantics. Current setup might not allow disabling reconnection.

Fixes https://github.com/Nerixyz/instagram_mqtt/issues/75

**This is a breaking change.**

### CODE REVIEW

**Comment by Nerixyz** [comment]
> This is a breaking change.

Kind of. I don't think the version should increment to `2.0` as there hasn't really changed anything. Yeah, semver says it should increment but 99% of the api hasn't changed. 

The issue would be that mqtts doesn't allow a boolean as `autoReconnect` which could be fixed easily in there.

**Comment by f0rr0** [comment]
Upto you :)

The current code is broken because of using `^` in `package.json` for `mqtts`. You can also consider having tighter version there.

**Comment by Nerixyz** [comment]
> The current code is broken because of using `^` in `package.json` for `mqtts`. You can also consider having tighter version there.

True. I'll change it in `mqtts`.

**Comment by Nerixyz** [comment]
It's fixed now (#78).

**Pull request closed without merging**
